### ISSUE TITLE
Caused by: com.serotonin.bacnet4j.exception.BACnetRuntimeException: No enumerated found for name 'analogInput'

### ISSUE THREAD

**Issue by duyanhan1995** [infiniteautomation/BACnet4J#26]
There is a method "forName(String):ObjectType" in the ObjectType Class.But when I try to get ObjectType by name, it's go wrong :

![image](https://user-images.githubusercontent.com/36763837/47210152-c52e5980-d3c4-11e8-8253-4076cba027eb.png)

**Comment by duyanhan1995** [comment]
Caused by: com.serotonin.bacnet4j.exception.BACnetRuntimeException: No enumerated found for name 'analogInput'
	at com.serotonin.bacnet4j.type.primitive.Enumerated.forName(Enumerated.java:95)
	at com.serotonin.bacnet4j.type.enumerated.ObjectType.forName(ObjectType.java:120)
	at com.yisquare.ba.scanner.config.PointConfig.getPointsAndProperties(PointConfig.java:47)
	at com.yisquare.ba.scanner.config.PointConfig$$EnhancerBySpringCGLIB$$c915987d.CGLIB$getPointsAndProperties$0(<generated>)
	at com.yisquare.ba.scanner.config.PointConfig$$EnhancerBySpringCGLIB$$c915987d$$FastClassBySpringCGLIB$$5b91cc6e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.yisquare.ba.scanner.config.PointConfig$$EnhancerBySpringCGLIB$$c915987d.getPointsAndProperties(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 32 more

**Comment by michelseiler** [comment]
You have to specify the string correctly.
AnalogInput is "analog-input".

`ObjectType forName = ObjectType.forName("analog-input");`

**Comment by duyanhan1995** [comment]
@michelseiler   Ok, I'll try

**Comment by duyanhan1995** [comment]
You successfully solved my problem, thank you @michelseiler 👍
